name: nearest_landmark
description: Nearest Landmark app.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  dio: ^2.1.3
  flutter_swiper : ^1.1.6
  rxdart: ^0.22.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
